import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";

import "./globals.css";
import { ModeToggle } from "@/components/mode-toggle";
import { TypographyP } from "@/components/typography";
import Link from "next/link";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Next.js shadcn/ui scaffold",
  description: "Generated by Leo Wang <https://wangrunlin.com>",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="sticky top-0 flex justify-between pt-8 px-48 border-collapse">
            <nav className="space-x-8">
              <Link href="/">
                <span>Leo Wang</span>
              </Link>
              <Link href="/about">
                <span>About</span>
              </Link>
            </nav>
            <ModeToggle />
          </header>

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
